# Generated by Django 5.2.17 on 2026-08-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='available_seats_not_above_total',
        ),
        migrations.AlterField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seats_reserved',
            field=models.PositiveIntegerField(),
        ),
    ]
