name: Terraform Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      terraform_action:
        required: true
        type: string
      working_directory:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_app_name: ${{ secrets.AZURE_WEBAPP_NAME }}
      TF_VAR_django_secret_key: ${{ secrets.DJANGO_SECRET_KEY }}
      TF_VAR_allowed_hosts: ${{ secrets.DJANGO_ALLOWED_HOSTS }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        if: ${{ inputs.terraform_action == 'apply' }}
        run: terraform apply -auto-approve tfplan
